# Generated by Django 5.0.3 on 2024-04-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='imagen',
        ),
    ]
